name: if action workflow  

on: push  

jobs:  
  
  test:
    runs-on: ubuntu-latest  
    steps:  
      - name: Run Test  
        run: |  
          ls ${{ github.workspace }}  
          echo Run Test  
  
  build: 
    needs: test  
    runs-on: ubuntu-latest  

    steps:  
      
      - name: Run Build  
        run: |  
          ls ${{ github.workspace }} 
          echo Run Build  

  deploy:  
    needs: build  
    runs-on: ubuntu-latest  

    steps:
      - name: Run Deploy1
        id: run_deploy1         
        run: |
          ls ${{github}}
          echo Run Deploy1
      - name: Run Deploy2 
        if: steps.run_deploy1.outcome == 'success'
        run: echo Run Deploy2